spring.datasource.url=jdbc:postgresql://localhost:5432/dispositivos_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Origins permitidos para CORS (usado en @CrossOrigin del controlador)
app.cors.allowed-origins=*