spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/dispositivos_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

service.api.key=${SERVICE_API_KEY}

# Origins permitidos para CORS (usado en @CrossOrigin del controlador)
app.cors.allowed-origins=http://localhost:8085